var num = 2463;
var a = num.toString();
var b = num.toString(2);
var c = num.toString(3);
var d = num.toString(4);
var e = num.toString(5);
var f = num.toString(6);
var g = num.toString(7);
var h = num.toString(8);
var i = num.toString(9);
var j = num.toString(16);

    console.log("Decimal: " + a);
    console.log("With Base as Two(Binary): "+b);
    console.log("With Base three: "+c);
    console.log("With Base Four: "+ d);
    console.log("With Base five: "+e);
    console.log("With Base six: "+f);
    console.log("With Base seven: "+g);
    console.log("With Base eight(Octal): "+h);
    console.log("With Base nine: "+i);
    console.log("With Base sixteen(Hexadecimal): "+j);

    document.write("Decimal: " + a +"<br/><br/>"); 
    document.write("With Base as Two(Binary): "+b +"<br/><br/>");
    document.write("With Base three: "+c +"<br/><br/>");
    document.write("With Base Four: "+ d +"<br/><br/>");
    document.write("With Base five: "+e +"<br/><br/>");
    document.write("With Base six: "+f +"<br/><br/>");
    document.write("With Base seven: "+g +"<br/><br/>");
    document.write("With Base eight(Octal): "+h +"<br/><br/>");
    document.write("With Base nine: "+i +"<br/><br/>");
    document.write("With Base sixteen(Hexadecimal): "+j +"<br/><br/>");
